version: '3.1'

services:
  docker-oss-cron:
    image: c1
    restart: always
    cap_add:
     - SYS_ADMIN
    devices:
      - '/dev/fuse'
    environment:
      BUCKET_NAME: test
      ACCESS_KEY: key
      ACCESS_KEY_SECRET: secret
      OSS_URL: http://oss-cn-beijing.aliyuncs.com